server:
  port: 7600
spring:
  application:
    name: technology-ms
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_technology
    username: root
    password: 1234
  flyway:
    url: jdbc:mysql://localhost:3306/db_technology
    user: root
    password: 1234
    locations: classpath:db/migration
  profiles:
    include: null
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: technology-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:7600"
kafka:
  topics:
    auth-login-admin: auth.login.admin
    generic-auth-logout: generic.auth.logout
    sync-technology-catalog: sync.technologies.catalog
    sync-technology-deleted: sync.technologies.deleted
    sync-technologies-capacities-match: sync.technologies.capacities.match
